name: build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '13.x'
          
      - name: Install packages
        run: npm install
      
      - name: Updated Readme
        run: npm run update-readme 
